import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { compile } from 'svelte/compiler';
import { resolve } from 'node:path';

const root = process.cwd();
const sourcePath = resolve(root, 'src/App.svelte');
const outputPath = resolve(root, 'src/App.runtime.js');

const source = readFileSync(sourcePath, 'utf8');
const result = compile(source, {
  filename: 'App.svelte',
  generate: 'client',
  css: 'injected',
  dev: false,
  runes: true
});

mkdirSync(resolve(root, 'src'), { recursive: true });
const banner = [
  '/** This file is generated by scripts/compile-svelte.mjs */',
  '/** Do not edit directly. Update src/App.svelte instead. */',
  ''
].join('\n');

writeFileSync(outputPath, `${banner}${result.js.code}\n`, 'utf8');
